### ISSUE TITLE
支持Vivo的手机的apk安装吗

### ISSUE THREAD

**Issue by chaooe** [codeskyblue/OppoApkInstaller#1]
这个支持Vivo的手机的apk安装吗？刚刚使用vivo X21,还是会弹出密码窗口。
![图片](https://user-images.githubusercontent.com/12910117/112805015-a65d4280-90a7-11eb-8f4a-b8f0ec1a1e89.png)

**Comment by codeskyblue** [comment]
没写完呢，还要改个包名。包名改成 sogou.mobile.explorer  估计可以

**Comment by codeskyblue** [comment]
@chaooe 你用最新的包试试，只是理论上可以，我还没有测试过

**Comment by chaooe** [comment]
@codeskyblue 可行，刚试了几部vivo的手机。 这个方案可以配置adb shell 的命令吗？是不是还需要配置一个服务才能可行
